dist: trusty
sudo: false
language: node_js
env:
  matrix:
    - SESEQUELIZE_DIALECT=postgres
    - SEQUELIZE_DIALECT=mysql
    - SEQUELIZE_DIALECT=sqlite
matrix:
  allow_failures:
    - SEQUELIZE_DIALECT=sqlite
node_js:
  - 8
services:
  - mysql
  - postgresql
install:
  - npm install -D
  - npm install -g nyc
addons:
  postgresql: "9.6"
script: "nyc npm test"
after_success:
  - "nyc report --reporter=text-lcov > coverage.lcov"
  - "bash <(curl -s https://codecov.io/bash)"
