dist: trusty
sudo: false
language: node_js
node_js:
  - 6
  - 8
services:
  - mysql
  - postgresql
install:
  - npm install -D
  - npm install -g nyc
addons:
  postgresql: "9.4"
script: "nyc npm test"
after_success:
  - "nyc report --reporter=text-lcov > coverage.lcov"
  - "bash <(curl -s https://codecov.io/bash)"
